### DISCUSSION TITLE
How to make the deployment compatible with Docker?

### DISCUSSION THREAD

**Discussion by guptakvgaurav** [TomSchimansky/CustomTkinter#313] [Q&A]
I am trying to write a program which will simulate sensors installed in a room. This setup require customtkinter and kafka, therefore i decided to bundle them up in a docker for deployment convenience. 

My problem is custom-tkinter is not able to initialize the `App()` problem due to absence (probably) of display module in the docker image. Hence, it comes up with the error and here are the logs

```
sensor_board_1  | Traceback (most recent call last):
sensor_board_1  |   File "/usr/src/app/./app.py", line 198, in <module>
sensor_board_1  |     app = App()
sensor_board_1  |   File "/usr/src/app/./app.py", line 28, in __init__
sensor_board_1  |     super().__init__()
sensor_board_1  |   File "/usr/local/lib/python3.9/site-packages/customtkinter/windows/ctk_tk.py", line 24, in __init__
sensor_board_1  |     super().__init__(*args, **kwargs)
sensor_board_1  |   File "/usr/local/lib/python3.9/tkinter/__init__.py", line 2270, in __init__
sensor_board_1  |     self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
sensor_board_1  | _tkinter.TclError: couldn't connect to display "0.0"
smart_home_sensor_board_1 exited with code 1

``` 

docker-compose.yml
```
# https://www.baeldung.com/ops/kafka-docker-setup
version: '2'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - 22181:2181
  
  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    ports:
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  
  sensor_board:
    build: ./sensor_board
    depends_on:
      - kafka
    volumes:
      - ./sensor_board:/usr/src/app
    environment:
      - DISPLAY=0.0
```

Dockerfile
```
FROM python:3.9 

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /usr/src/app/

CMD [ "python", "./app.py" ]
```
